-- local harpoon = require("harpoon")
--
-- harpoon:setup()

-- basic telescope configuration
-- local conf = require("telescope.config").values
--
-- local function toggle_telescope(harpoon_files)
--     local file_paths = {}
--     for _, item in ipairs(harpoon_files.items) do
--         table.insert(file_paths, item.value)
--     end
--
--     require("telescope.pickers").new({}, {
--         prompt_title = "Harpoon",
--         finder = require("telescope.finders").new_table({
--             results = file_paths,
--         }),
--         previewer = conf.file_previewer({}),
--         sorter = conf.generic_sorter({}),
--     }):find()
-- end
--
-- vim.keymap.set("n", "<leader>h", function()
-- 	harpoon:list():add()
-- 	print("added to harpoon")
-- end, { desc = "Add current buffer to harpoon" })
--
-- vim.keymap.set("n", "<leader>vh", function()
-- 	print("viewing")
-- 	toggle_telescope(harpoon:list())
-- end, { desc = "Open harpoon window" })
